
package com.sumingjie.client;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.2
 * 
 */
@WebService(name = "PictureWebService", targetNamespace = "http://service.sumingjie.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface PictureWebService {


    /**
     * 
     * @return
     *     returns java.util.List<com.sumingjie.client.Picture>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAllPictures", targetNamespace = "http://service.sumingjie.com/", className = "com.sumingjie.client.GetAllPictures")
    @ResponseWrapper(localName = "getAllPicturesResponse", targetNamespace = "http://service.sumingjie.com/", className = "com.sumingjie.client.GetAllPicturesResponse")
    @Action(input = "http://service.sumingjie.com/PictureWebService/getAllPicturesRequest", output = "http://service.sumingjie.com/PictureWebService/getAllPicturesResponse")
    public List<Picture> getAllPictures();

    /**
     * 
     * @param q
     * @return
     *     returns java.util.List<com.sumingjie.client.Picture>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findPictures", targetNamespace = "http://service.sumingjie.com/", className = "com.sumingjie.client.FindPictures")
    @ResponseWrapper(localName = "findPicturesResponse", targetNamespace = "http://service.sumingjie.com/", className = "com.sumingjie.client.FindPicturesResponse")
    @Action(input = "http://service.sumingjie.com/PictureWebService/findPicturesRequest", output = "http://service.sumingjie.com/PictureWebService/findPicturesResponse")
    public List<Picture> findPictures(
        @WebParam(name = "q", targetNamespace = "")
        MyRequest q);

}
